AWS_ACCESS_KEY_ID: "AKIAJX7PSXBK2CIGG6XQ"
AWS_SECRET_ACCESS_KEY: "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"

production: 
  AWS_BUCKET: sharebnb-production
  FACEBOOK_KEY: 271627206333794
  FACEBOOK_SECRET: ffbc94dce094141b5a3c6061ed14c026
development:
  AWS_BUCKET: sharebnb-dev
  SENDGRID_USERNAME: app22306718@heroku.com
  SENDGRID_PASSWORD: btd3nl0f
  FACEBOOK_KEY: 533169453453642
  FACEBOOK_SECRET: 4f31ad19ca0a650b94120912c7a6e9f5